### ISSUE TITLE
Why can't I recover my previous wallet address with mnemonics? Has  wallet been audited?

### ISSUE THREAD

**Issue by yingnengd** [argentlabs/argent-x#760]
Why can't I recover my previous wallet address with mnemonics? Has  wallet been audited?

**Comment by janek26** [comment]
that's because of changes to the underlying technology :) 
We need to migrate users to new accounts due to StarkWare not supporting the old ones at some point.

If you're more into the tech, it's because the `Proxy` contract changed.

And no, the wallet is not audited, the contracts are. Which doesn't protect from breaking changes like this.

**Starknet is alpha** and we always emphasised this.


You can recover your old wallet by checking out tag v3.x.x from GitHub and do the migration by updating to v4.x..x afterwards btw.
